import abc
from collections.abc import Hashable

from green_eggs.data_types import PrivMsg as PrivMsg

class CommandTrigger(Hashable, abc.ABC, metaclass=abc.ABCMeta):
    def __and__(self, other: CommandTrigger) -> AndTrigger: ...
    def __eq__(self, other) -> bool: ...
    def __or__(self, other: CommandTrigger) -> OrTrigger: ...
    @abc.abstractmethod
    def check(self, message: PrivMsg) -> bool: ...

class LogicTrigger(CommandTrigger, abc.ABC, metaclass=abc.ABCMeta):
    def __init__(self, *triggers: CommandTrigger) -> None: ...
    def __hash__(self) -> int: ...

class AndTrigger(LogicTrigger):
    def check(self, message: PrivMsg) -> bool: ...

class OrTrigger(LogicTrigger):
    def check(self, message: PrivMsg) -> bool: ...

class FirstWordTrigger(CommandTrigger):
    def __init__(self, value: str, case_sensitive: bool = ...) -> None: ...
    def __hash__(self) -> int: ...
    def check(self, message: PrivMsg) -> bool: ...

class SenderIsModTrigger(CommandTrigger):
    def __hash__(self) -> int: ...
    def check(self, message: PrivMsg) -> bool: ...
