from types import TracebackType
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple, Type, Union

from aiologger import Logger as Logger

UrlParams = Union[
    Mapping[Any, Any], Mapping[Any, Sequence[Any]], Sequence[Tuple[Any, Any]], Sequence[Tuple[Any, Sequence[Any]]]
]

def exclude_non_empty(**kwargs): ...

class TwitchApi:
    def __init__(self, client_id: str, token: str, logger: Logger) -> None: ...
    async def __aenter__(self) -> TwitchApi: ...
    async def __aexit__(
        self, exc_type: Optional[Type[BaseException]], exc_val: Optional[BaseException], exc_tb: Optional[TracebackType]
    ): ...
    async def start_commercial(self, broadcaster_id: str, length: int): ...
    async def get_extension_analytics(
        self,
        *,
        after: str = ...,
        ended_at: str = ...,
        extension_id: str = ...,
        first: int = ...,
        started_at: str = ...,
        type_: str = ...,
    ): ...
    async def get_game_analytics(
        self,
        *,
        after: str = ...,
        ended_at: str = ...,
        first: int = ...,
        game_id: str = ...,
        started_at: str = ...,
        type_: str = ...,
    ): ...
    async def get_bits_leaderboard(
        self, *, count: int = ..., period: str = ..., started_at: str = ..., user_id: str = ...
    ): ...
    async def get_cheermotes(self, *, broadcaster_id: str = ...): ...
    async def get_extension_transactions(
        self, extension_id: str, *, id_: Union[str, List[str]] = ..., after: str = ..., first: int = ...
    ): ...
    async def get_channel_information(self, broadcaster_id: str): ...
    async def modify_channel_information(
        self,
        broadcaster_id: str,
        *,
        game_id: str = ...,
        broadcaster_language: str = ...,
        title: str = ...,
        delay: int = ...,
    ): ...
    async def get_channel_editors(self, broadcaster_id: str): ...
    async def create_custom_rewards(
        self,
        broadcaster_id: str,
        title: str,
        cost: int,
        *,
        prompt: str = ...,
        is_enabled: bool = ...,
        background_color: str = ...,
        is_user_input_required: bool = ...,
        is_max_per_stream_enabled: bool = ...,
        max_per_stream: int = ...,
        is_max_per_user_per_stream_enabled: bool = ...,
        max_per_user_per_stream: int = ...,
        is_global_cooldown_enabled: bool = ...,
        global_cooldown_seconds: int = ...,
        should_redemptions_skip_request_queue: bool = ...,
    ): ...
    async def delete_custom_reward(self, broadcaster_id: str, id_: str): ...
    async def get_custom_reward(
        self, broadcaster_id: str, *, id_: Union[str, List[str]] = ..., only_manageable_rewards: bool = ...
    ): ...
    async def get_custom_reward_redemption(
        self,
        broadcaster_id: str,
        reward_id: str,
        *,
        id_: Union[str, List[str]] = ...,
        status: str = ...,
        sort: str = ...,
        after: str = ...,
        first: int = ...,
    ): ...
    async def update_custom_reward(
        self,
        broadcaster_id: str,
        id_: str,
        *,
        title: str = ...,
        prompt: str = ...,
        cost: int = ...,
        background_color: str = ...,
        is_enabled: bool = ...,
        is_user_input_required: bool = ...,
        is_max_per_stream_enabled: bool = ...,
        max_per_stream: int = ...,
        is_max_per_user_per_stream_enabled: bool = ...,
        max_per_user_per_stream: int = ...,
        is_global_cooldown_enabled: bool = ...,
        global_cooldown_seconds: int = ...,
        is_paused: bool = ...,
        should_redemptions_skip_request_queue: bool = ...,
    ): ...
    async def update_redemption_status(
        self, id_: Union[str, List[str]], broadcaster_id: str, reward_id: str, status: str
    ): ...
    async def get_channel_emotes(self, broadcaster_id: str): ...
    async def get_global_emotes(self): ...
    async def get_emote_sets(self, emote_set_id: str): ...
    async def get_channel_chat_badges(self, broadcaster_id: str): ...
    async def get_global_chat_badges(self): ...
    async def create_clip(self, broadcaster_id: str, *, has_delay: bool = ...): ...
    async def get_clips(
        self,
        broadcaster_id: str,
        game_id: str,
        id_: Union[str, List[str]],
        *,
        after: str = ...,
        before: str = ...,
        ended_at: str = ...,
        first: int = ...,
        started_at: str = ...,
    ): ...
    async def get_code_status(self): ...
    async def get_drops_entitlements(
        self,
        *,
        id_: str = ...,
        user_id: str = ...,
        game_id: str = ...,
        fulfillment_status: str = ...,
        after: str = ...,
        first: int = ...,
    ): ...
    async def update_drops_entitlements(self, *, entitlement_ids: List[str] = ..., fulfillment_status: str = ...): ...
    async def redeem_code(self, *, code: str = ..., user_id: int = ...): ...
    async def get_extension_configuration_segment(self, broadcaster_id: str, extension_id: str, segment: str): ...
    async def set_extension_configuration_segment(
        self, extension_id: str, segment: str, *, broadcaster_id: str = ..., content: str = ..., version: str = ...
    ): ...
    async def set_extension_required_configuration(
        self, broadcaster_id: str, extension_id: str, extension_version: str, configuration_version: str
    ): ...
    async def send_extension_pubsub_message(
        self, target: List[str], broadcaster_id: str, is_global_broadcast: bool, message: str
    ): ...
    async def get_live_channels(self, extension_id: str, *, first: int = ..., after: str = ...): ...
    async def get_extension_secrets(self): ...
    async def create_extension_secret(self, *, delay: int = ...): ...
    async def send_extension_chat_message(
        self, broadcaster_id: str, text: str, extension_id: str, extension_version: str
    ): ...
    async def get_extensions(self, extension_id: str, *, extension_version: str = ...): ...
    async def get_released_extensions(self, extension_id: str, *, extension_version: str = ...): ...
    async def get_extension_bits_products(self, *, should_include_all: bool = ...): ...
    async def update_extension_bits_product(
        self,
        sku: str,
        cost: Dict[str, Any],
        display_name: str,
        *,
        in_development: bool = ...,
        expiration: str = ...,
        is_broadcast: bool = ...,
    ): ...
    async def create_eventsub_subscription(
        self, type_: str, version: str, condition: Dict[str, Any], transport: Dict[str, Any]
    ): ...
    async def delete_eventsub_subscription(self, id_: str): ...
    async def get_eventsub_subscriptions(self, *, status: str = ..., type_: str = ..., after: str = ...): ...
    async def get_top_games(self, *, after: str = ..., before: str = ..., first: int = ...): ...
    async def get_games(self, id_: str, name: str): ...
    async def get_creator_goals(self, broadcaster_id: str): ...
    async def get_hype_train_events(
        self, broadcaster_id: str, *, first: int = ..., id_: str = ..., cursor: str = ...
    ): ...
    async def check_automod_status(self, broadcaster_id: str, msg_id: str, msg_text: str, user_id: str): ...
    async def manage_held_automod_messages(self, user_id: str, msg_id: str, action: str): ...
    async def get_banned_events(
        self, broadcaster_id: str, *, user_id: Union[str, List[str]] = ..., after: str = ..., first: str = ...
    ): ...
    async def get_banned_users(
        self,
        broadcaster_id: str,
        *,
        user_id: Union[str, List[str]] = ...,
        first: str = ...,
        after: str = ...,
        before: str = ...,
    ): ...
    async def get_moderators(
        self, broadcaster_id: str, *, user_id: Union[str, List[str]] = ..., first: str = ..., after: str = ...
    ): ...
    async def get_moderator_events(
        self, broadcaster_id: str, *, user_id: Union[str, List[str]] = ..., after: str = ..., first: str = ...
    ): ...
    async def get_polls(
        self, broadcaster_id: str, *, id_: Union[str, List[str]] = ..., after: str = ..., first: str = ...
    ): ...
    async def create_poll(
        self,
        broadcaster_id: str,
        title: str,
        choices: List[Dict[str, Any]],
        duration: int,
        *,
        bits_voting_enabled: bool = ...,
        bits_per_vote: int = ...,
        channel_points_voting_enabled: bool = ...,
        channel_points_per_vote: int = ...,
    ): ...
    async def end_poll(self, broadcaster_id: str, id_: str, status: str): ...
    async def get_predictions(
        self, broadcaster_id: str, *, id_: Union[str, List[str]] = ..., after: str = ..., first: str = ...
    ): ...
    async def create_prediction(
        self, broadcaster_id: str, title: str, outcomes: List[Dict[str, Any]], prediction_window: int
    ): ...
    async def end_prediction(self, broadcaster_id: str, id_: str, status: str, *, winning_outcome_id: str = ...): ...
    async def get_channel_stream_schedule(
        self,
        broadcaster_id: str,
        *,
        id_: Union[str, List[str]] = ...,
        start_time: str = ...,
        utc_offset: str = ...,
        first: int = ...,
        after: str = ...,
    ): ...
    async def get_channel_icalendar(self, broadcaster_id: str): ...
    async def update_channel_stream_schedule(
        self,
        broadcaster_id: str,
        *,
        is_vacation_enabled: bool = ...,
        vacation_start_time: str = ...,
        vacation_end_time: str = ...,
        timezone: str = ...,
    ): ...
    async def create_channel_stream_schedule_segment(
        self,
        broadcaster_id: str,
        start_time: str,
        timezone: str,
        is_recurring: bool,
        *,
        duration: str = ...,
        category_id: str = ...,
        title: str = ...,
    ): ...
    async def update_channel_stream_schedule_segment(
        self,
        broadcaster_id: str,
        id_: str,
        *,
        start_time: str = ...,
        duration: str = ...,
        category_id: str = ...,
        title: str = ...,
        is_canceled: bool = ...,
        timezone: str = ...,
    ): ...
    async def delete_channel_stream_schedule_segment(self, broadcaster_id: str, id_: str): ...
    async def search_categories(self, query: str, *, first: int = ..., after: str = ...): ...
    async def search_channels(self, query: str, *, first: int = ..., after: str = ..., live_only: bool = ...): ...
    async def get_stream_key(self, broadcaster_id: str): ...
    async def get_streams(
        self,
        *,
        after: str = ...,
        before: str = ...,
        first: int = ...,
        game_id: str = ...,
        language: str = ...,
        user_id: str = ...,
        user_login: str = ...,
    ): ...
    async def get_followed_streams(self, user_id: str, *, after: str = ..., first: int = ...): ...
    async def create_stream_marker(self, user_id: str, *, description: str = ...): ...
    async def get_stream_markers(
        self, user_id: str, video_id: str, *, after: str = ..., before: str = ..., first: str = ...
    ): ...
    async def get_broadcaster_subscriptions(
        self, broadcaster_id: str, *, user_id: str = ..., after: str = ..., first: str = ...
    ): ...
    async def check_user_subscription(self, broadcaster_id: str, user_id: str): ...
    async def get_all_stream_tags(self, *, after: str = ..., first: int = ..., tag_id: str = ...): ...
    async def get_stream_tags(self, broadcaster_id: str): ...
    async def replace_stream_tags(self, broadcaster_id: str, *, tag_ids: List[str] = ...): ...
    async def get_channel_teams(self, broadcaster_id: str): ...
    async def get_teams(self, *, name: str = ..., id_: str = ...): ...
    async def get_users(self, *, id_: Union[str, List[str]] = ..., login: Union[str, List[str]] = ...): ...
    async def update_user(self, *, description: str = ...): ...
    async def get_users_follows(self, *, after: str = ..., first: int = ..., from_id: str = ..., to_id: str = ...): ...
    async def get_user_block_list(self, broadcaster_id: str, *, first: int = ..., after: str = ...): ...
    async def block_user(self, target_user_id: str, *, source_context: str = ..., reason: str = ...): ...
    async def unblock_user(self, target_user_id: str): ...
    async def get_user_extensions(self): ...
    async def get_user_active_extensions(self, *, user_id: str = ...): ...
    async def update_user_extensions(self): ...
    async def get_videos(
        self,
        id_: Union[str, List[str]],
        user_id: str,
        game_id: str,
        *,
        after: str = ...,
        before: str = ...,
        first: str = ...,
        language: str = ...,
        period: str = ...,
        sort: str = ...,
        type_: str = ...,
    ): ...
    async def delete_videos(self, id_: Union[str, List[str]]): ...
    async def get_webhook_subscriptions(self, *, after: str = ..., first: str = ...): ...
