class ChannelPresenceRaceCondition(Exception): ...

class CooldownNotElapsed(Exception):
    remaining: float
    def __init__(self, remaining: float, *args, **kwargs) -> None: ...

class GlobalCooldownNotElapsed(CooldownNotElapsed): ...
class UserCooldownNotElapsed(CooldownNotElapsed): ...
