name: "Lint PR"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            feat
            fix
          wip: true
          validateSingleCommit: true
