name: "Test Code"
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test_code:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 5
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        timeout-minutes: 5
      - name: "Install poetry"
        uses: abatilo/actions-poetry@v2.2.0
        timeout-minutes: 5
      - name: "Sanity check"
        run: poetry check
        timeout-minutes: 5
      - name: "Setup env"
        run: poetry install
        timeout-minutes: 10
      - name: "Tests"
        run: poetry run pytest --cov-report=xml --cov=green_eggs tests
        timeout-minutes: 5
        continue-on-error: ${{ matrix.os == 'windows-latest' && matrix.python-version != '3.7' }}
      - name: "Upload coverage report"
        uses: codecov/codecov-action@v3
        timeout-minutes: 5
